import { Urbanist , Onest } from "next/font/google";
import "./globals.css";

const urbanist = Urbanist({subsets : ["latin"]});

const onest = Onest({subsets : ["latin"]});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${onest.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
