import { Urbanist , Comic_Neue } from "next/font/google";
import "./globals.css";

const urbanist = Urbanist({subsets : ["latin"]});

const test = Comic_Neue({subsets : ["latin"] , weight : ['400']});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${test.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
